age = input('Enter your age in years:')
print('You are ...')
print(int(age) * int(365), 'days old, or')
print(int(age) * int(365) * int(24), 'hours old, or')
print(int(age) * int(365) * int(24) * int(60), 'minutes old, or')
print(int(age) * int(365) * int(24) * int(60) * int(60), 'seconds old.')